---
- name: Configuración de infraestructura en la nube
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Crear Cloud Load Balancer
      gcp_compute_forwarding_rule:
        name: my-load-balancer
        ip_protocol: TCP
        port_range: 80
        backend_service: my-backend-service
        target: my-target-pool
        region: us-east41
        project: your-project-id
        auth_kind: serviceaccount
        service_account_file: /path/to/service_account_file.json

    - name: Crear Cloud DNS
      gcp_dns_managed_zone:
        name: my-dns-zone
        dns_name: my-domain.com
        description: My DNS Zone
        project: your-project-id
        auth_kind: serviceaccount
        service_account_file: /path/to/service_account_file.json

    - name: Crear Bastion
      gcp_compute_instance:
        name: my-bastion
        machine_type: n1-standard-1
        zone: us-east41-a
        image: ubuntu-1804-bionic-v20200529
        project: your-project-id
        auth_kind: serviceaccount
        service_account_file: /path/to/service_account_file.json

    - name: Crear GKE Cluster
      gcp_container_cluster:
        name: my-cluster
        initial_node_count: 3
        zone: us-east41-a
        project: your-project-id
        auth_kind: serviceaccount
        service_account_file: /path/to/service_account_file.json

    - name: Crear Container Registry
      gcp_container_registry:
        name: my-container-registry
        project: your-project-id
        auth_kind: serviceaccount
        service_account_file: /path/to/service_account_file.json

    - name: Crear Cloud SQL (PostgreSQL)
      gcp_sql_database_instance:
        name: my-sql-instance
        backend_type: SECOND_GEN
        database_version: POSTGRES_9_6
        region: us-east41
        project: your-project-id
        auth_kind: serviceaccount
        service_account_file: /path/to/service_account_file.json
